before_script:
  - /opt/rh/rh-python36/root/usr/bin/pip3.6 install virtualenv
  - virtualenv -p /opt/rh/rh-python36/root/usr/bin/python3.6 venv
  - ./venv/bin/pip3 install -r requirements.txt


stages:
  - test

test:
  stage: test
  script:
    - ./venv/bin/python3 setup.py test
